"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { cacheReading, readCachedReadings } from "../lib/browser-reading-cache";
import { ENGINE_SUPPORTED_SYMBOLS } from "../lib/engine-supported-symbols";

type Tone = "break" | "pressure" | "forming-pressure" | "contested" | "forming-expansion" | "expansion" | "durable";
type View = "combined" | "positional" | "investor";
type Stock = { ticker:string; name:string; reading:string; tone:Tone; e:number; p:number; phase:string; window:string; nearPath:string[]; nextInflection:string; pressure:string; potential:string; score:number; episodes:number; forward:number; interruption:string; renewal:string; chart:string; confidence:number; story:string; skyDate?:string; engineVersion?:string; natalFingerprint?:string; cacheState?:"publication"|"browser"|"fresh" };
type MacroTone = "neutral" | "expansion" | "pressure" | "watch";
type MacroEvent = { name:string; date:string; tone:MacroTone; meaning:string; day?:string; month?:string };
type EngineEvent = { label?:string; state?:string; phase?:string; start?:string; end?:string };
type EngineModel = { version?:string; current:{state?:string;direction?:string;expansionStage?:string;pressureStage?:string;story?:string}; scores:{expansion?:number;pressure?:number;cycleRunway?:number;forwardLeadership?:number}; paths?:{tactical?:EngineEvent[];strategic?:EngineEvent[]}; windows?:{rerating?:EngineEvent;pressure?:EngineEvent;breakRisk?:EngineEvent}; cycle?:{level?:string;score?:number;episodes?:EngineEvent[]}; natal?:{chartType?:string;chartAuthority?:string;primaryChartId?:string;companyName?:string;reliability?:number} };
type EnginePayload = { symbol?:string;skyDate?:string;engineVersion?:string;natalFingerprint?:string;chartBasisLabel?:string;chartConfidence?:number;row?:{name?:string;symbol?:string;company_name?:string;natal_chart_type?:string;natal_reliability?:number;astro_model?:EngineModel} };
type ReplayContact = { planet?:string;targetPlanet?:string;aspect?:string;orb?:number;score?:number;text?:string };
type ReplayPayload = {
  success?:boolean;
  version?:string;
  input?:{ticker?:string;date?:string;forwardDays?:number;chartId?:string|null};
  resolvedCompany?:Record<string,unknown>;
  natalResearch?:{selectedChartId?:string|null;preferredChartId?:string|null;candidateCount?:number;candidates?:Array<Record<string,unknown>>;researchCase?:unknown;validationEligibility?:string};
  natalReliability?:Record<string,unknown>;
  macroSnapshot?:Record<string,unknown>;
  sectorContext?:Record<string,unknown>;
  transitReceptorFit?:Record<string,unknown>;
  astroModel?:EngineModel&Record<string,unknown>;
  replaySummary?:{expression?:string;confidence?:string;regime?:string;phaseFit?:string;expansionScore?:number;pressureScore?:number;rawExpansionScore?:number;rawPressureScore?:number;leadershipProbability?:number;volatility?:number|string;catalystWindow?:unknown;environmentSignature?:unknown;clusterDensity?:unknown;activeClusters?:unknown[];overlapIntensity?:unknown;natalArchetype?:string;elementBias?:string;dominantPlanets?:string[];topContacts?:ReplayContact[];forwardPath?:Record<string,unknown>;chartValidation?:Record<string,unknown>;contextNote?:string};
  research?:{natal?:unknown;baseTransits?:unknown;relevantEclipses?:unknown;eclipseHits?:unknown;replay?:unknown;windows?:unknown};
  error?:string;
};
type AdmissionRequest = { id:number;symbol:string;companyName:string;exchange:string;status:"preparing-evidence"|"candidate-ready"|"owner-review"|"needs-evidence";classification:string;evidenceStage:string;requestCount:number;lastRequestedAt:string;isin?:string|null;listingDate?:string|null;candidateDate?:string|null;sourceLabel?:string|null;historyFlags?:string[] };
type AddResult = { status:string;message:string;stock?:Stock;request?:AdmissionRequest };

const starterStocks: Stock[] = [
  { ticker:"BHARTIARTL", name:"Bharti Airtel", reading:"Expansion strengthening", tone:"expansion", e:72,p:55,phase:"Strengthening",window:"Active · 20 Aug",nearPath:["Expansion strengthening","Rerating established · 11–26 Sep","Continuation pause · 11 Oct"],nextInflection:"11 Sep · Rerating established",pressure:"No structural pressure sequence",potential:"Exceptional rerating structure",score:90,episodes:4,forward:77,interruption:"No Break-Risk in measured runway",renewal:"Rerating established · 11 Sep",chart:"Verified listing chart",confidence:77,story:"Expansion is strengthening again. No slow pressure pattern. Forward leadership remains constructive." },
  { ticker:"HDFCBANK", name:"HDFC Bank", reading:"Rerating established", tone:"durable", e:79,p:53,phase:"Established",window:"20–27 Aug",nearPath:["Rerating established","Expansion strengthens · 11 Sep","Pressure begins forming · 11 Sep–11 Oct"],nextInflection:"11 Sep · Expansion strengthens",pressure:"Pressure begins forming in September",potential:"Exceptional repeated expansion",score:88,episodes:3,forward:74,interruption:"Peak pressure · 26 Oct–10 Nov; no Break-Risk",renewal:"Continuation resumes after November pressure",chart:"Verified merger-effective chart",confidence:75,story:"Rerating is established. Expansion leads, with an early pressure warning beginning in September." },
  { ticker:"TCS", name:"Tata Consultancy Services", reading:"Pressure in control", tone:"pressure", e:70,p:66,phase:"Pressure sovereign",window:"Active · 20 Aug",nearPath:["Pressure in control","Rerating intact, but pausing · 27 Aug","Continuation through October"],nextInflection:"27 Aug · Support reappears",pressure:"Current pressure; no qualified Break-Risk",potential:"Exceptional long-cycle runway",score:87,episodes:4,forward:70,interruption:"Current pressure interrupts expression",renewal:"Rerating pause begins · 27 Aug",chart:"Verified listing chart",confidence:75,story:"Pressure is governing now, while the measured 24-month structure retains four productive expansion episodes." },
  { ticker:"PFC", name:"Power Finance Corporation", reading:"Expansion strengthening", tone:"expansion", e:69,p:56,phase:"Strengthening",window:"Active · 20 Aug",nearPath:["Expansion strengthening","Rerating established · 27 Aug–26 Sep","Continuation pause · 11 Oct"],nextInflection:"27 Aug · Rerating established",pressure:"No structural pressure sequence",potential:"Exceptional repeated expansion",score:85,episodes:4,forward:74,interruption:"No Break-Risk in measured runway",renewal:"Rerating established · 27 Aug",chart:"Verified listing chart",confidence:75,story:"Expansion is strengthening and develops into an established rerating window across late August and September." },
  { ticker:"TITAN", name:"Titan Company", reading:"Rerating established", tone:"forming-pressure", e:75,p:63,phase:"Established · vulnerability forming",window:"Active · 20 Aug",nearPath:["Rerating established","Continuation compresses · 26 Sep","Early pressure warning develops"],nextInflection:"26 Sep · Continuation compresses",pressure:"Early vulnerability; expansion still leads",potential:"Exceptional rerating structure",score:85,episodes:3,forward:73,interruption:"High pressure candidate in early 2027; not Break-Risk",renewal:"Three expansion episodes across the runway",chart:"Verified incorporation chart",confidence:75,story:"Rerating is established. Risk is rising, but expansion still has control; this is an early warning, not active pressure." },
  { ticker:"RELIANCE", name:"Reliance Industries", reading:"Rerating established", tone:"durable", e:73,p:56,phase:"Established",window:"Active · 20 Aug",nearPath:["Rerating established","Continuation pause · 11 Sep","Expansion remains intact through October"],nextInflection:"11 Sep · Continuation compresses",pressure:"No structural pressure sequence",potential:"Strong repeated expansion",score:83,episodes:2,forward:74,interruption:"No Break-Risk in measured runway",renewal:"Two distinct productive episodes",chart:"Verified listing chart",confidence:95,story:"Rerating is established. The next phase is a pause within expansion rather than a structural pressure sequence." },
  { ticker:"NEWGEN", name:"Newgen Software", reading:"Expansion strengthening", tone:"forming-pressure", e:71,p:63,phase:"Strengthening · vulnerability forming",window:"Active · 20 Aug",nearPath:["Expansion strengthening","Pressure activates · 27 Aug","Rerating established · by 11 Sep"],nextInflection:"27 Aug · Pressure activates",pressure:"Early warning; expansion still leads",potential:"Strong role-validated runway",score:82,episodes:3,forward:76,interruption:"Pressure phase · February 2027; no Break-Risk",renewal:"Rerating renewal · 10 Mar 2027",chart:"Role-validated history",confidence:95,story:"Expansion is strengthening. Pressure begins to activate before the rerating becomes established; distinct chart roles remain unblended." },
  { ticker:"LT", name:"Larsen & Toubro", reading:"Peak pressure", tone:"pressure", e:65,p:73,phase:"Pressure culmination",window:"20–27 Aug",nearPath:["Peak pressure","Brief support · 27 Aug","Compressed rerating + early warning · 11 Sep"],nextInflection:"27 Aug · Brief support",pressure:"Pressure has not yet cleared",potential:"Strong but delayed runway",score:80,episodes:1,forward:96,interruption:"Current pressure precedes the productive episode",renewal:"One long productive expansion episode",chart:"Verified incorporation chart",confidence:75,story:"Peak pressure is active. A short burst of support does not yet establish recovery, although forward leadership is high." },
  { ticker:"ICICIBANK", name:"ICICI Bank", reading:"Pressure in control", tone:"pressure", e:66,p:78,phase:"Pressure sovereign",window:"Active · 20 Aug",nearPath:["Pressure in control","Peak pressure · 27 Aug","Brief support; pressure not cleared"],nextInflection:"27 Aug · Pressure culmination",pressure:"High structural discipline; no Break-Risk",potential:"Moderate future runway",score:70,episodes:2,forward:75,interruption:"Two severe candidates remain unqualified",renewal:"Expansion strengthens · 6 Sep 2027",chart:"Verified incorporation chart",confidence:75,story:"Pressure is in control. Brief support does not yet mean recovery; the measured runway contains two later expansion episodes." },
  { ticker:"IFCI", name:"IFCI", reading:"Expansion strengthening", tone:"expansion", e:80,p:65,phase:"Strengthening",window:"20–27 Aug",nearPath:["Expansion strengthening","Rerating established · 11 Sep","Continuation pauses · 26 Sep"],nextInflection:"11 Sep · Rerating established",pressure:"Qualified Break-Risk · Feb 2027",potential:"Moderate · interrupted runway",score:66,episodes:1,forward:72,interruption:"Break-Risk · 4–23 Feb 2027",renewal:"Two post-pressure reformation episodes",chart:"Verified corporatisation chart",confidence:95,story:"Expansion is strengthening now, but a qualified structural Break-Risk interrupts the longer runway in February 2027." }
];

const PUBLICATION_SKY_DATE = "2026-08-20";

function cleanTicker(value:string){return value.trim().toUpperCase().replace(/\.(NS|BO)$/i,"").replace(/[^A-Z0-9&-]/g,"")}
function currentSkyDate(){const parts=new Intl.DateTimeFormat("en-GB",{timeZone:"Asia/Kolkata",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(new Date());const value=(kind:string)=>parts.find(part=>part.type===kind)?.value||"";return `${value("year")}-${value("month")}-${value("day")}`}
function skyDateLabel(value?:string){if(!value)return "Current IST sky";return new Date(`${value}T12:00:00`).toLocaleDateString("en-GB",{timeZone:"Asia/Kolkata",day:"numeric",month:"short",year:"numeric"})}
function labelFromTicker(ticker:string){return ticker.replace(/&/g," & ").replace(/-/g," ")}
function rangeLabel(windowValue?:EngineEvent|null){if(!windowValue)return "No separate window mapped";const label=windowValue.label||windowValue.state||windowValue.phase||"Mapped window";const dates=[windowValue.start,windowValue.end].filter(Boolean).join("–");return dates?`${label} · ${dates}`:label}
function toneFromState(state:string,direction:string):Tone{const text=`${state} ${direction}`.toUpperCase();if(text.includes("BREAK"))return "break";if(text.includes("PRESSURE")&&text.includes("FORM"))return "forming-pressure";if(text.includes("PRESSURE"))return "pressure";if(text.includes("DURABLE"))return "durable";if(text.includes("EXPANSION")||text.includes("RERATING"))return "expansion";return "contested"}
function adaptEngineReading(payload:EnginePayload):Stock|null{
  const raw=payload?.row;const model=raw?.astro_model;if(!raw||!model?.current||!model?.scores)return null;
  const currentState=model.current.state||"Current astro state";
  const ticker=cleanTicker(raw.name||raw.symbol||payload.symbol||"");if(!ticker)return null;
  const tactical=(model.paths?.tactical||[]).slice(0,3).map((event:EngineEvent)=>rangeLabel(event));
  const strategic=(model.paths?.strategic||[]);const pressureWindow=model.windows?.pressure||model.windows?.breakRisk;
  const renewalEvent=strategic.find((event:EngineEvent)=>/EXPANSION|RERATING|SUPPORT|RECOVER/i.test(String(event?.label||event?.state||"")));
  const episodes=Array.isArray(model.cycle?.episodes)?model.cycle.episodes.length:0;
  const chartType=raw.natal_chart_type||model.natal?.chartType||model.natal?.chartAuthority||"approved";
  const confidence=Number(payload.chartConfidence??model.natal?.reliability??raw.natal_reliability??50);
  return {ticker,name:raw.company_name||model.natal?.companyName||labelFromTicker(ticker),reading:currentState,tone:toneFromState(currentState,model.current.direction||""),e:Number(model.scores.expansion||0),p:Number(model.scores.pressure||0),phase:[model.current.expansionStage,model.current.pressureStage].filter(Boolean).join(" · ")||currentState,window:rangeLabel(model.windows?.rerating||model.windows?.pressure),nearPath:tactical.length?tactical:[currentState],nextInflection:tactical[1]||"No separate turning point mapped",pressure:rangeLabel(pressureWindow),potential:`${model.cycle?.level||"Measured"} long-cycle structure`,score:Number(model.cycle?.score??model.scores.cycleRunway??0),episodes,forward:Number(model.scores.forwardLeadership||0),interruption:rangeLabel(model.windows?.breakRisk||model.windows?.pressure),renewal:renewalEvent?rangeLabel(renewalEvent):"No separate renewal mapped",chart:payload.chartBasisLabel||`Verified ${String(chartType).toLowerCase()} chart`,confidence,story:model.current.story||"The Astro engine returned an approved current reading.",skyDate:payload.skyDate,engineVersion:payload.engineVersion||model.version||"v37.9.14",natalFingerprint:payload.natalFingerprint,cacheState:"fresh"};
}
async function fetchApprovedReading(value:string){const ticker=cleanTicker(value);const response=await fetch(`/api/get-stocks?symbols=${encodeURIComponent(`${ticker}.NS`)}`,{headers:{accept:"application/json"}});const rows=await response.json() as Array<EnginePayload["row"]>;const row=Array.isArray(rows)?rows[0]:undefined;const payload={success:Boolean(row),status:row?"verified-engine-reading":"natal-unavailable",symbol:`${ticker}.NS`,skyDate:(row as {as_of_date?:string;sky_date?:string}|undefined)?.as_of_date||(row as {sky_date?:string}|undefined)?.sky_date||currentSkyDate(),engineVersion:(row?.astro_model?.version)||"v37.9.14",natalFingerprint:(row as {natal_chart_id?:string}|undefined)?.natal_chart_id||ticker,row,error:row?undefined:"This company is not in the approved natal registry."};return {response:{ok:response.ok&&Boolean(row)},payload:payload as EnginePayload&{status?:string;reason?:string;error?:string}}}
async function fetchHistoricalReplay(ticker:string,date:string){const response=await fetch(`/api/replay-lab?ticker=${encodeURIComponent(`${cleanTicker(ticker)}.NS`)}&date=${encodeURIComponent(date)}&forwardDays=730&raw=1`,{headers:{accept:"application/json"}});const payload=await response.json() as ReplayPayload;return {response,payload}}
async function requestCompanyAdmission(value:string):Promise<AddResult>{return {status:"natal-unavailable",message:`${cleanTicker(value)} is not yet in the approved natal registry. Add its verified natal record to the engine before publishing a subscriber reading.`}}

const macroNow: MacroEvent[] = [
  {name:"Lunar eclipse in Aquarius",date:"Applying · exact 28 Aug",tone:"watch",meaning:"Turning-point and volatility intensity are elevated; natal contacts decide continuation, reversal or rotation."},
  {name:"Solar eclipse in Cancer",date:"Separating · through 11 Sep",tone:"watch",meaning:"The reset field remains active, but its immediate authority is gradually waning."},
  {name:"Saturn–Venus opposition",date:"Active · through 25 Aug",tone:"pressure",meaning:"Restraint around liquidity, valuation and confidence can produce delay, compression or selectivity."},
  {name:"Jupiter–Venus sextile",date:"Active · through 22 Aug",tone:"expansion",meaning:"Supports rerating and preference for quality where the stock’s natal Venus or Jupiter is receptive."}
];
const macroNext: MacroEvent[] = [
  {name:"Mercury–Rahu opposition",date:"25 Aug · in 4.8 days",tone:"pressure",day:"25",month:"AUG",meaning:"Narrative heat rises; headlines, messaging and expectations can become reactive or produce false signals."},
  {name:"Lunar eclipse in Aquarius",date:"28 Aug · in 7.7 days",tone:"watch",day:"28",month:"AUG",meaning:"A turning-point field increases volatility; each stock’s natal contacts decide the direction of expression."},
  {name:"Mars–Saturn square",date:"1 Sep · in 11.9 days",tone:"pressure",day:"01",month:"SEP",meaning:"Force meets restraint, favouring friction, delay or disciplined execution depending on natal response."}
];
const toneLabel: Record<Tone,string> = { break:"Break-Risk", pressure:"Pressure", "forming-pressure":"Pressure forming", contested:"Contested", "forming-expansion":"Expansion forming", expansion:"Expansion", durable:"Durable expansion" };

function ScorePair({e,p}:{e:number;p:number}) { return <div className="score-pair" aria-label={`Expansion ${e} out of 100; pressure ${p} out of 100`}><span className="e-score">E {e}</span><span className="p-score">P {p}</span></div> }
function TonePill({tone,children}:{tone:Tone;children?:React.ReactNode}) { return <span className={`tone tone-${tone}`}><i />{children || toneLabel[tone]}</span> }
function StockCell({s}:{s:Stock}) { return <div className="stock-cell"><span className="stock-avatar">{s.ticker.slice(0,2)}</span><span><b>{s.name}</b><small>{s.ticker}.NS</small></span></div> }
function Path({items}:{items:string[]}) { return <div className="path">{items.map((item,i)=><span key={item}><i className={i===0?"now":""}/>{item}</span>)}</div> }
function RowButton({s,onSelect,children}:{s:Stock;onSelect:(s:Stock)=>void;children:React.ReactNode}) { return <tr onClick={()=>onSelect(s)} tabIndex={0} onKeyDown={e=>{if(e.key==="Enter")onSelect(s)}}>{children}</tr> }

export default function Dashboard() {
  const [view,setView] = useState<View>("combined"); const [defaultView,setDefaultView] = useState<View>("combined");
  const [sort,setSort] = useState("score"); const [query,setQuery] = useState(""); const [selected,setSelected] = useState<Stock|null>(null);
  const [addOpen,setAddOpen] = useState(false); const [fullStock,setFullStock] = useState<Stock|null>(null);
  const [allStocks,setAllStocks] = useState<Stock[]>(starterStocks);
  const [watchlist,setWatchlist] = useState<string[]>(starterStocks.map(s=>s.ticker));
  useEffect(()=>{ const timer=window.setTimeout(()=>{void (async()=>{const saved=window.localStorage.getItem("finlumen-default-view") as View|null; if(saved&&["combined","positional","investor"].includes(saved)){setView(saved);setDefaultView(saved)} let savedTickers=starterStocks.map(s=>s.ticker);const savedWatchlist=window.localStorage.getItem("finlumen-watchlist");if(savedWatchlist){try{const parsed=JSON.parse(savedWatchlist);if(Array.isArray(parsed))savedTickers=parsed.filter((ticker):ticker is string=>typeof ticker==="string").slice(0,100)}catch{}}let cachedEntries:Awaited<ReturnType<typeof readCachedReadings<Stock>>> = [];try{cachedEntries=await readCachedReadings<Stock>()}catch{}const cached=cachedEntries.map(entry=>({...entry.reading,cacheState:"browser" as const}));const merged=[...starterStocks,...cached].reduce<Stock[]>((rows,item)=>[...rows.filter(row=>row.ticker!==item.ticker),item],[]);setAllStocks(merged);setWatchlist(savedTickers);const params=new URLSearchParams(window.location.search);if(params.get("view")==="card"){const ticker=cleanTicker(params.get("stock")||"");setFullStock(merged.find(s=>s.ticker===ticker)||null)}const today=currentSkyDate();const cachedByTicker=new Map(cachedEntries.map(entry=>[entry.ticker,entry]));const refreshTicker=async(ticker:string)=>{const cachedEntry=cachedByTicker.get(ticker);if(cachedEntry?.skyDate===today)return;try{const {response,payload}=await fetchApprovedReading(ticker);if(!response.ok)return;const refreshed=adaptEngineReading(payload);if(!refreshed)return;await cacheReading({ticker:refreshed.ticker,skyDate:refreshed.skyDate||today,engineVersion:refreshed.engineVersion||"v37.9.14",natalFingerprint:refreshed.natalFingerprint||refreshed.ticker,cachedAt:new Date().toISOString(),reading:refreshed});setAllStocks(current=>[...current.filter(item=>item.ticker!==refreshed.ticker),refreshed])}catch{}};for(let index=0;index<savedTickers.length;index+=4){await Promise.all(savedTickers.slice(index,index+4).map(refreshTicker))}})()},0); return()=>window.clearTimeout(timer) },[]);
  const visible=useMemo(()=>allStocks.filter(s=>watchlist.includes(s.ticker)).filter(s=>`${s.name} ${s.ticker}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==="score"?b.score-a.score:sort==="expansion"?b.e-a.e:sort==="pressure"?b.p-a.p:sort==="confidence"?b.confidence-a.confidence:a.name.localeCompare(b.name)),[allStocks,watchlist,query,sort]);
  const makeDefault=()=>{window.localStorage.setItem("finlumen-default-view",view);setDefaultView(view)};
  const saveWatchlist=(next:string[])=>{setWatchlist(next);window.localStorage.setItem("finlumen-watchlist",JSON.stringify(next))};
  const addTicker=(ticker:string)=>{if(watchlist.includes(ticker))return;if(watchlist.length>=100)throw new Error("Your 100-stock table is full.");saveWatchlist([...watchlist,ticker])};
  const removeTicker=(ticker:string)=>saveWatchlist(watchlist.filter(item=>item!==ticker));
  const requestAdd=async(value:string)=>{
    const ticker=cleanTicker(value);if(!ticker)return {status:"invalid" as const,message:"Enter a valid company name or exchange ticker."};
    const existing=allStocks.find(stock=>stock.ticker===ticker||stock.name.toUpperCase()===value.trim().toUpperCase());if(existing){addTicker(existing.ticker);return {status:"added" as const,stock:existing,message:`${existing.name} was added from its cached approved reading.`}}
    const {response,payload}=await fetchApprovedReading(value);
    if(!response.ok){
      if(payload.status==="natal-unavailable"||payload.status==="unavailable")return requestCompanyAdmission(value);
      return {status:payload.status||"unavailable",message:payload.reason||payload.error||"No approved natal reading is available."};
    }
    const stock=adaptEngineReading(payload);if(!stock)return {status:"unavailable" as const,message:"The engine response did not contain an approved subscriber reading."};
    await cacheReading({ticker:stock.ticker,skyDate:stock.skyDate||"unknown",engineVersion:stock.engineVersion||"v37.9.14",natalFingerprint:stock.natalFingerprint||stock.ticker,cachedAt:new Date().toISOString(),reading:stock});
    setAllStocks(current=>[...current.filter(item=>item.ticker!==stock.ticker),stock]);addTicker(stock.ticker);return {status:"added" as const,stock,message:`${stock.name} was calculated once and cached on this device.`};
  };
  if(fullStock)return <FullStockPage stock={fullStock}/>;
  return <main>
    <header className="topbar"><a className="brand" href="#top"><span className="brand-mark">FL</span><span><strong>FIN–LUMEN</strong><small>PURE ASTRO RESEARCH</small></span></a><div className="header-right"><span className="asof"><b>Sky date</b> {skyDateLabel(allStocks.find(stock=>stock.skyDate)?.skyDate)} · IST</span><a className="icon-button" href="/owner-review" aria-label="Owner review">T</a></div></header>
    <div className="shell" id="top">
      <section className="welcome"><div><span className="eyebrow">Subscriber dashboard <i className="private-beta">Private beta</i></span><h1>Financial astrology,<br/><em>clearly mapped.</em></h1><p>A structured view of market conditions and company-specific astrological cycles.</p></div><div className="watch-count"><span>MY STOCKS</span><strong>{watchlist.length} <small>/ 100</small></strong><button onClick={()=>setAddOpen(true)}>＋ Add stock</button></div></section>
      <section className="macro-grid" aria-label="Market astro environment">
        <article className="macro-card macro-current macro-state-pressure"><div className="card-kicker"><span className="live-dot"/>ACTIVE NOW <span className="panel-state pressure">PRESSURE</span><time>20 AUG 2026</time></div><h2>High pressure <span>· Turning-point field active</span></h2><p>High pressure is controlling immediate expression while the market is between a separating and an applying eclipse.</p><div className="macro-body"><div className="macro-scores"><div><span>PRESSURE</span><b>39</b><small>/100</small></div><div><span>EXPANSION</span><b>12</b><small>/100</small></div><div><span>TURNING POINT</span><b>22</b><small>/100</small></div><div><span>MOON</span><b className="word-score">Scorpio</b><small>Emotional</small></div></div><div className="event-list">{macroNow.map(event=><div className={`event-row macro-event-${event.tone}`} key={event.name}><span className={`event-icon ${event.tone}`}/><span className="event-copy"><b>{event.name}</b><small>{event.date}</small><em>{event.meaning}</em></span><span className={`macro-tag ${event.tone}`}>{event.tone}</span></div>)}</div></div></article>
        <article className="macro-card macro-next macro-state-watch"><div className="card-kicker">NEXT 30 DAYS <span className="panel-state watch">WATCH · PRESSURE DEVELOPING</span><time>WHAT DEVELOPS NEXT</time></div><h2>Pressure sequence <span>· Turning-point field</span></h2><p>The next sequence intensifies narrative heat and restraint before the eclipse field begins to separate.</p><div className="next-events">{macroNext.map(event=><div className={`next-row macro-event-${event.tone}`} key={event.name}><span className={`date-box ${event.tone}`}>{event.day}<small>{event.month}</small></span><span className="event-copy"><b>{event.name}</b><small>{event.date}</small><em>{event.meaning}</em></span><span className={`macro-tag ${event.tone}`}>{event.tone}</span></div>)}</div></article>
      </section>
      <section className="workspace">
        <div className="workspace-head"><div><span className="eyebrow">My astro watchlist</span><h2>Read the horizon that matters to you.</h2></div><div className="controls"><label className="search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Find a stock" aria-label="Find a stock"/></label><select value={sort} onChange={e=>setSort(e.target.value)} aria-label="Sort stocks"><option value="score">Highest 24m potential</option><option value="expansion">Highest expansion</option><option value="pressure">Highest pressure</option><option value="confidence">Highest confidence</option><option value="name">Alphabetical</option></select></div></div>
        <div className="viewbar"><div className="view-tabs" role="tablist">{(["combined","positional","investor"] as View[]).map(v=><button role="tab" aria-selected={view===v} className={view===v?"active":""} onClick={()=>setView(v)} key={v}>{v==="combined"?"Combined overview":v==="positional"?"Positional · 45 days":"Investor · 24 months"}</button>)}</div><button className={`default-button ${defaultView===view?"saved":""}`} onClick={makeDefault}>{defaultView===view?"✓ Default view":"Make this my default"}</button></div>
        <div className="table-wrap">{view==="combined"&&<CombinedTable stocks={visible} onSelect={setSelected}/>} {view==="positional"&&<PositionalTable stocks={visible} onSelect={setSelected}/>} {view==="investor"&&<InvestorTable stocks={visible} onSelect={setSelected}/>}</div>
        <div className="table-foot"><span>Showing {visible.length} of {watchlist.length} cached readings</span><span>Cache-first · one approved calculation per company and sky date · v37.9.14 unchanged</span><span>Scores describe astrological structure and intensity; they are not financial forecasts.</span></div>
        <nav className="below-table-tabs" aria-label="Table resources"><a href="#replay">↺ Historical Replay</a><a href="#reading-guide">? Reading guide</a></nav>
      </section>
      <ReplaySection stocks={allStocks.filter(stock=>watchlist.includes(stock.ticker))}/>
      <AdmissionQueue />
      <ReadingGuide />
      <footer className="disclaimer"><b>Important:</b> Fin-Lumen presents astrological research derived from a fixed methodology. It does not provide personalised investment advice, technical analysis, financial forecasts or guaranteed outcomes. Scores compare astrological structure and intensity within the model; they are not probabilities. Subscribers should use independent financial judgement and professional advice where appropriate.</footer>
    </div>
    {selected&&<StockDrawer stock={selected} onClose={()=>setSelected(null)} onRemove={()=>{removeTicker(selected.ticker);setSelected(null)}}/>}
    {addOpen&&<AddStockModal stocks={allStocks} watchlist={watchlist} onRequestAdd={requestAdd} onClose={()=>setAddOpen(false)}/>}
  </main>
}

function CombinedTable({stocks,onSelect}:{stocks:Stock[];onSelect:(s:Stock)=>void}) { return <table><thead><tr><th>Stock</th><th>Current reading</th><th>E / P</th><th>Phase & active window</th><th>Near-term path</th><th>24-month astro potential</th><th>Score</th><th>Principal risk</th><th>Chart confidence</th></tr></thead><tbody>{stocks.map(s=><RowButton s={s} onSelect={onSelect} key={s.ticker}><td><StockCell s={s}/></td><td><TonePill tone={s.tone}>{s.reading}</TonePill></td><td><ScorePair e={s.e} p={s.p}/></td><td><b>{s.phase}</b><small>{s.window}</small></td><td><Path items={s.nearPath}/></td><td><b>{s.potential}</b><small>{s.episodes} productive episode{s.episodes===1?"":"s"}</small></td><td><span className={`potential-score ${s.score>=85?"high":s.score>=75?"good":"moderate"}`}>{s.score}<small>/100</small></span></td><td><b>{s.pressure}</b></td><td><b>{s.chart}</b><small>{s.confidence}/100 reliability</small></td></RowButton>)}</tbody></table> }
function PositionalTable({stocks,onSelect}:{stocks:Stock[];onSelect:(s:Stock)=>void}) { return <table><thead><tr><th>Stock</th><th>Current reading</th><th>E / P</th><th>Phase maturity</th><th>Current window</th><th>Ordered 45-day path</th><th>Next material turning point</th><th>Pressure character</th><th>Confidence</th></tr></thead><tbody>{stocks.map(s=><RowButton s={s} onSelect={onSelect} key={s.ticker}><td><StockCell s={s}/></td><td><TonePill tone={s.tone}>{s.reading}</TonePill></td><td><ScorePair e={s.e} p={s.p}/></td><td><b>{s.phase}</b></td><td><b>{s.window}</b></td><td><Path items={s.nearPath}/></td><td><b>{s.nextInflection}</b></td><td><b>{s.pressure}</b></td><td><span className="confidence-score">{s.confidence}<small>/100</small></span><small>{s.chart}</small></td></RowButton>)}</tbody></table> }
function InvestorTable({stocks,onSelect}:{stocks:Stock[];onSelect:(s:Stock)=>void}) { return <table><thead><tr><th>Stock</th><th>Current cycle position</th><th>24-month astro potential</th><th>Score</th><th>Expansion episodes</th><th>Forward leadership</th><th>Major interruption</th><th>Next renewal</th><th>Chart confidence</th></tr></thead><tbody>{stocks.map(s=><RowButton s={s} onSelect={onSelect} key={s.ticker}><td><StockCell s={s}/></td><td><TonePill tone={s.tone}>{s.phase}</TonePill><small>{s.reading}</small></td><td><b>{s.potential}</b></td><td><span className={`potential-score ${s.score>=85?"high":s.score>=75?"good":"moderate"}`}>{s.score}<small>/100</small></span></td><td><b>{s.episodes}</b><small>productive phases</small></td><td><span className="confidence-score">{s.forward}<small>/100</small></span></td><td><b>{s.interruption}</b></td><td><b>{s.renewal}</b></td><td><b>{s.chart}</b><small>{s.confidence}/100 reliability</small></td></RowButton>)}</tbody></table> }

function readingMeaning(s:Stock){
  if(s.tone==="pressure"||s.tone==="break")return "Restraining conditions currently have more authority. This can delay, compress or distort expression; it does not automatically mean a price decline.";
  if(s.tone==="forming-pressure")return "Support remains present, but pressure is developing. Treat this as an early-warning phase rather than established pressure.";
  if(s.tone==="durable")return "A mature supportive structure is governing now and has shown resilience through ordinary pressure.";
  if(s.tone==="expansion"||s.tone==="forming-expansion")return "Supportive conditions have more authority than pressure and are strengthening, although the path can still contain pauses.";
  return "Support and pressure are closely balanced, so the next dated change carries more interpretive weight.";
}

function showValue(value:unknown):string{
  if(value===null||value===undefined||value==="")return "—";
  if(typeof value==="string"||typeof value==="number")return String(value);
  if(typeof value==="boolean")return value?"Yes":"No";
  if(Array.isArray(value))return value.map(showValue).join(" · ")||"—";
  return JSON.stringify(value)||String(value);
}

function ResearchEvidence({payload}:{payload:ReplayPayload}){
  const summary=payload.replaySummary||{};
  const company=payload.resolvedCompany||{};
  const natal=payload.natalReliability||{};
  const macro=payload.macroSnapshot||{};
  const contacts=summary.topContacts||[];
  const model=payload.astroModel;
  return <div className="engine-research-body">
    <div className="research-status"><span className="live-dot"/><div><b>Fin-Lumen Personal Research 1.0 · v37.9.14</b><small>Historical sky {payload.input?.date||showValue(macro.date)} · Lahiri sidereal · Swiss Ephemeris</small></div></div>
    <div className="research-score-grid">
      <div><small>MODEL EXPANSION</small><b>{showValue(summary.expansionScore??model?.scores?.expansion)}<i>/100</i></b><span>Raw {showValue(summary.rawExpansionScore)}</span></div>
      <div><small>MODEL PRESSURE</small><b>{showValue(summary.pressureScore??model?.scores?.pressure)}<i>/100</i></b><span>Raw {showValue(summary.rawPressureScore)}</span></div>
      <div><small>LEADERSHIP</small><b>{showValue(summary.leadershipProbability??model?.scores?.forwardLeadership)}<i>/100</i></b><span>{showValue(summary.regime)}</span></div>
      <div><small>EXPRESSION</small><strong>{showValue(summary.expression||model?.current?.state)}</strong><span>{showValue(summary.confidence)}</span></div>
    </div>
    <div className="research-sections">
      <section><span className="eyebrow">Natal authority</span><dl><div><dt>Company</dt><dd>{showValue(company.companyName)}</dd></div><div><dt>Selected chart</dt><dd>{showValue(payload.natalResearch?.selectedChartId||payload.input?.chartId)}</dd></div><div><dt>Chart type</dt><dd>{showValue(natal.chartType||company.chartType)}</dd></div><div><dt>Date and time</dt><dd>{showValue(natal.birthDate||company.birthDate)} · {showValue(natal.birthTime||company.birthTime)}</dd></div><div><dt>Place</dt><dd>{showValue(natal.city||company.city)}, {showValue(company.country)}</dd></div><div><dt>Timezone</dt><dd>{showValue(natal.timezone||company.timezone)}</dd></div><div><dt>Source</dt><dd>{showValue(company.natalSource)}</dd></div><div><dt>Validation</dt><dd>{showValue(payload.natalResearch?.validationEligibility)}</dd></div></dl></section>
      <section><span className="eyebrow">Macro sky</span><dl><div><dt>Environment</dt><dd>{showValue(macro.environmentLabel||macro.environment)}</dd></div><div><dt>Dominant force</dt><dd>{showValue(macro.dominantForce)}</dd></div><div><dt>Pressure / Expansion</dt><dd>{showValue(macro.pressure)} / {showValue(macro.expansion)}</dd></div><div><dt>Volatility</dt><dd>{showValue(macro.volatility)}</dd></div><div><dt>Moon</dt><dd>{showValue(macro.moon)}</dd></div><div><dt>Headline</dt><dd>{showValue(macro.headline)}</dd></div><div><dt>Main support</dt><dd>{showValue(macro.mainOpportunity)}</dd></div><div><dt>Main risk</dt><dd>{showValue(macro.mainRisk)}</dd></div></dl></section>
      <section className="contacts-section"><span className="eyebrow">Strongest transit-to-natal contacts</span>{contacts.length?<ol>{contacts.map((contact,index)=><li key={`${contact.planet}-${contact.targetPlanet}-${index}`}><b>{contact.text||`${showValue(contact.planet)} ${showValue(contact.aspect)} natal ${showValue(contact.targetPlanet)}`}</b><span>Orb {showValue(contact.orb)}° · score {showValue(contact.score)}</span></li>)}</ol>:<p>No ranked contact ledger was returned for this sky date.</p>}</section>
    </div>
    <details className="research-ledger"><summary>Temporal paths, windows and cycle ledger <i>＋</i></summary><pre>{JSON.stringify({current:model?.current,scores:model?.scores,paths:model?.paths,windows:model?.windows,cycle:model?.cycle,forwardPath:summary.forwardPath,chartValidation:summary.chartValidation},null,2)}</pre></details>
    <details className="research-ledger"><summary>Natal candidates and reliability record <i>＋</i></summary><pre>{JSON.stringify({resolvedCompany:payload.resolvedCompany,natalReliability:payload.natalReliability,natalResearch:payload.natalResearch},null,2)}</pre></details>
    <details className="research-ledger"><summary>Macro, sector and receptor-fit ledger <i>＋</i></summary><pre>{JSON.stringify({macroSnapshot:payload.macroSnapshot,sectorContext:payload.sectorContext,transitReceptorFit:payload.transitReceptorFit},null,2)}</pre></details>
    <details className="research-ledger"><summary>Complete v37.9.14 research payload <i>＋</i></summary><p>Full natal positions, historical transits, eclipses, contacts, window scan and model output returned by the authoritative engine.</p><pre>{JSON.stringify(payload,null,2)}</pre></details>
  </div>
}

function EngineResearchView({ticker,date}:{ticker:string;date?:string}){
  const [payload,setPayload]=useState<ReplayPayload|null>(null);
  const [loading,setLoading]=useState(false);
  const [error,setError]=useState("");
  const load=async()=>{if(payload||loading)return;setLoading(true);setError("");try{const result=await fetchHistoricalReplay(ticker,date);if(!result.response.ok||!result.payload.success)throw new Error(result.payload.error||"The full research record could not be loaded.");setPayload(result.payload)}catch(reason){setError(reason instanceof Error?reason.message:"The full research record could not be loaded.")}finally{setLoading(false)}};
  return <details className="engine-research" onToggle={event=>{if(event.currentTarget.open)void load()}}><summary><span><small>RESEARCH VIEW · v37.9.14</small><b>Open the complete astrology and evidence ledger</b></span><i>＋</i></summary>{loading&&<p className="research-loading">Calculating the selected sky and loading the full research record…</p>}{error&&<div className="research-error"><b>Research record unavailable</b><p>{error}</p><button onClick={()=>{setError("");void load()}}>Try again</button></div>}{payload&&<ResearchEvidence payload={payload}/>}</details>
}

function StockReading({s,deep=false}:{s:Stock;deep?:boolean}){
  return <div className="stock-reading">
    <section className="reading-lead"><span className="eyebrow">Current reading</span><TonePill tone={s.tone}>{s.reading}</TonePill><h2>{s.story}</h2><p className="phase-meaning"><b>What this means:</b> {readingMeaning(s)}</p></section>
    <div className="drawer-stats"><div><span>EXPANSION</span><b>{s.e}<small>/100</small></b></div><div><span>PRESSURE</span><b>{s.p}<small>/100</small></b></div><div><span>ACTIVE WINDOW</span><b className="text-stat">{s.window}</b></div><div><span>24M ASTRO POTENTIAL</span><b>{s.score}<small>/100</small></b></div></div>
    <section className="quick-grid"><div><span className="eyebrow">Near-term path</span><Path items={s.nearPath}/></div><div><span className="eyebrow">Long-cycle structure</span><h3>{s.potential}</h3><p>{s.episodes} productive expansion episode{s.episodes===1?"":"s"} in the measured runway.</p></div><div><span className="eyebrow">Principal risk</span><h3>{s.interruption}</h3><p>{s.pressure}</p></div><div><span className="eyebrow">Chart confidence</span><h3>{s.confidence}/100</h3><p>{s.chart}</p></div></section>
    {deep&&<div className="deep-reading">
      <section><div className="section-title"><span className="eyebrow">Positional · 45 days</span><h3>The ordered near-term sequence</h3></div><div className="research-grid"><div><small>PHASE MATURITY</small><b>{s.phase}</b></div><div><small>CURRENT WINDOW</small><b>{s.window}</b></div><div><small>NEXT TURNING POINT</small><b>{s.nextInflection}</b></div><div><small>PRESSURE CHARACTER</small><b>{s.pressure}</b></div></div><Path items={s.nearPath}/></section>
      <section><div className="section-title"><span className="eyebrow">Investor · 24 months</span><h3>{s.potential}</h3></div><div className="research-grid"><div><small>ASTRO POTENTIAL</small><b>{s.score}/100</b></div><div><small>EXPANSION EPISODES</small><b>{s.episodes}</b></div><div><small>FORWARD LEADERSHIP</small><b>{s.forward}/100</b></div><div><small>PRINCIPAL INTERRUPTION</small><b>{s.interruption}</b></div></div><p className="renewal"><b>Next renewal:</b> {s.renewal}</p></section>
      <section><div className="section-title"><span className="eyebrow">Why this reading</span><h3>Astro engine interpretation</h3></div><p>{s.story}</p><p>Expansion and pressure are measured independently; the governing phase reflects their authority, maturity and ordered sequence rather than a simple subtraction of one score from the other.</p></section>
      <section><div className="section-title"><span className="eyebrow">Chart basis</span><h3>{s.chart}</h3></div><p><b>{s.confidence}/100 chart reliability.</b> This measures confidence in the approved natal basis—not confidence that a market outcome must occur.</p></section>
      <details className="astro-basis"><summary><span><small>ASTROLOGICAL BASIS</small><b>See how this reading was formed</b></span><i>＋</i></summary><div className="basis-grid"><div><small>NATAL AUTHORITY</small><b>{s.chart}</b><p>{s.confidence}/100 reliability for the approved company-event chart.</p></div><div><small>CURRENT SKY BALANCE</small><b>Expansion {s.e} · Pressure {s.p}</b><p>The scores are independent intensities; the reading is not produced by simply subtracting one from the other.</p></div><div><small>TEMPORAL EVIDENCE</small><b>{s.phase}</b><p>{s.nearPath.join(" → ")}</p></div><div><small>INTERPRETIVE RULE</small><b>Authority, maturity and sequence</b><p>The Astro engine resolves which force governs now, what is forming next and whether the longer structure survives interruption.</p></div></div><p className="basis-note">This summary contains the approved publication evidence. Open Research View below for the complete v37.9.14 natal, transit, eclipse, window and scoring ledger.</p></details>
      <EngineResearchView ticker={s.ticker} date={s.skyDate||currentSkyDate()}/>
    </div>}
  </div>
}

function StockDrawer({stock:s,onClose,onRemove}:{stock:Stock;onClose:()=>void;onRemove:()=>void}) {
  const [expanded,setExpanded]=useState(false); const url=`/?stock=${s.ticker}&view=card`;
  return <div className="drawer-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><aside className={`drawer ${expanded?"drawer-expanded":""}`} role="dialog" aria-modal="true" aria-label={`${s.name} stock reading`}><div className="drawer-toolbar"><StockCell s={s}/><div><button onClick={()=>setExpanded(v=>!v)} aria-pressed={expanded}>{expanded?"↙ Summary":"↗ Expand"}</button><a href={url} target="_blank" rel="noreferrer">Open in new tab</a><button className="remove-stock" onClick={onRemove}>Remove</button><button className="close" onClick={onClose} aria-label="Close stock reading">×</button></div></div><StockReading s={s} deep={expanded}/><a className="drawer-replay" href={`/?replayStock=${s.ticker}#replay`}>Replay {s.ticker}</a></aside></div>
}

function FullStockPage({stock:s}:{stock:Stock}){
  return <main className="full-stock-page"><header className="topbar"><Link className="brand" href="/"><span className="brand-mark">FL</span><span><strong>FIN–LUMEN</strong><small>PURE ASTRO RESEARCH</small></span></Link><div className="header-right"><span className="asof"><b>Sky date</b> {skyDateLabel(s.skyDate)} · IST</span></div></header><div className="full-stock-shell"><div className="full-stock-nav"><Link href="/">← Back to dashboard</Link><span>Full stock reading</span></div><article className="full-stock-card"><div className="full-stock-head"><StockCell s={s}/><TonePill tone={s.tone}>{s.reading}</TonePill></div><StockReading s={s} deep/><Link className="full-replay-link" href={`/?replayStock=${s.ticker}#replay`}>Historical replay</Link></article><footer className="disclaimer"><b>Important:</b> This is astrological research, not personalised investment advice or a financial forecast. Scores describe structure and intensity within Fin-Lumen’s fixed methodology.</footer></div></main>
}

function ReplaySection({stocks}:{stocks:Stock[]}){
  const [mode,setMode]=useState<"sky"|"archive">("sky"); const [date,setDate]=useState("2025-08-15"); const [ticker,setTicker]=useState(stocks[0]?.ticker||""); const [payload,setPayload]=useState<ReplayPayload|null>(null);const [archiveStock,setArchiveStock]=useState<Stock|null>(null);const [loading,setLoading]=useState(false);const [error,setError]=useState("");const today=currentSkyDate();
  useEffect(()=>{const timer=window.setTimeout(()=>{const requested=new URLSearchParams(window.location.search).get("replayStock")?.replace(".NS","").toUpperCase();if(requested&&stocks.some(s=>s.ticker===requested))setTicker(requested)},0);return()=>window.clearTimeout(timer)},[stocks]);
  const company=stocks.find(s=>s.ticker===ticker);
  const clear=()=>{setPayload(null);setArchiveStock(null);setError("")};
  const run=async()=>{clear();if(!ticker||!date)return;setLoading(true);try{if(mode==="archive"){if(date!==PUBLICATION_SKY_DATE||!company)throw new Error("No sealed publication was stored for this company on that date. The private beta archive currently contains the 20 Aug 2026 publication batch.");setArchiveStock(company);return}const result=await fetchHistoricalReplay(ticker,date);if(!result.response.ok||!result.payload.success)throw new Error(result.payload.error||"The historical sky could not be calculated.");setPayload(result.payload)}catch(reason){setError(reason instanceof Error?reason.message:"The historical sky could not be calculated.")}finally{setLoading(false)}};
  return <section className="replay" id="replay"><div className="replay-copy"><span className="eyebrow">Historical research</span><h2>Replay Lab</h2><p>Run v37.9.14 under a past sky—or retrieve an immutable reading from a stored publication batch.</p><ul><li>Historical transits are calculated for the selected date.</li><li>Present-day data cannot rewrite the result.</li><li>Price is not used by the astrology engine.</li></ul></div><div className="replay-panel"><div className="replay-tabs"><button className={mode==="sky"?"active":""} onClick={()=>{setMode("sky");clear()}}>Historical Sky Replay</button><button className={mode==="archive"?"active":""} onClick={()=>{setMode("archive");setDate(PUBLICATION_SKY_DATE);clear()}}>Published Archive</button></div><p>{mode==="sky"?"Recalculate v37.9.14 using only the selected historical sky and the approved natal chart. Replays are not limited by the dashboard.":"Open the exact cached reading from an available publication date."}</p><div className="replay-controls"><label><span>COMPANY</span><select value={ticker} onChange={e=>{setTicker(e.target.value);clear()}}>{stocks.map(s=><option value={s.ticker} key={s.ticker}>{s.name}</option>)}</select></label><label><span>{mode==="sky"?"REPLAY DATE":"PUBLICATION DATE"}</span><input type="date" value={date} min="1990-01-01" max={mode==="sky"?today:PUBLICATION_SKY_DATE} onChange={e=>{setDate(e.target.value);clear()}}/></label><button onClick={()=>void run()} disabled={loading||!ticker||!date}>{loading?"Calculating historical sky…":`View ${mode==="sky"?"historical sky":"published reading"}`}</button></div>{error&&<div className="replay-error"><b>Replay unavailable</b><p>{error}</p></div>}{archiveStock&&<div className="replay-output"><div className="replay-result"><span className="live-dot"/><div><b>{archiveStock.name} · Published Archive · 20 Aug 2026</b><small>Exact private-beta publication reading. It is retrieved rather than recalculated.</small></div><button onClick={clear}>Close result</button></div><StockReading s={archiveStock}/></div>}{payload&&<div className="replay-output"><div className="replay-result"><span className="live-dot"/><div><b>{company?.name} · Historical Sky Replay · {new Date(`${date}T12:00:00`).toLocaleDateString("en-GB",{day:"numeric",month:"short",year:"numeric"})}</b><small>Calculated by v37.9.14 from the selected historical sky. No present-day market information was used.</small></div><button onClick={clear}>Return to controls</button></div><ResearchEvidence payload={payload}/></div>}</div></section>
}

function ReadingGuide(){
  const phases=[
    ["Expansion","Supportive astrological conditions have more authority than pressure. This can improve momentum, participation or opportunity, but it does not promise a price rise."],
    ["Rerating","Expansion has become persistent or repeated enough to support a more meaningful change in how the stock expresses leadership. It is an astrological structure—not a valuation or return forecast."],
    ["Rerating strengthening","The rerating structure is gaining authority but has not yet reached its most established phase."],
    ["Rerating established","The rerating structure is active and mature enough to govern the current reading, subject to any stated pressure or interruption."],
    ["Compressed rerating","The rerating structure remains intact, but pressure is restricting its expression. Progress may be slower, selective or interrupted rather than absent."],
    ["Volatile expansion","Support remains stronger than pressure, but volatile contacts can produce an uneven path, rapid reversals or exaggerated reactions."],
    ["Volatile rerating","A meaningful rerating structure is active, but volatility can disrupt how cleanly it expresses. The supportive structure and the unstable path are both real."],
    ["Pressure","Restraining conditions have authority. They can delay, compress or distort expression; pressure does not automatically mean that every stock must fall."],
    ["Pressure forming","A pressure pattern is developing but has not yet taken control. It is an early-warning state, not the same as active pressure."],
    ["Peak pressure","The pressure sequence is near its strongest measured phase. Relief afterward is possible, but recovery requires a later supportive structure."],
    ["Durable expansion","Support repeats across the measured runway and remains resilient through ordinary pressure. It describes structural persistence, not guaranteed performance."],
    ["Break-Risk","A specifically qualified destructive structural-pressure network. It is more serious than ordinary pressure and is never inferred merely from a long quiet period."]
  ];
  const terms=[
    ["E / P","Expansion and Pressure intensity, each measured independently out of 100."],
    ["Current reading","The governing astrological condition on the selected sky date."],
    ["Phase maturity","Whether a condition is forming, strengthening, established, mature or exhausting."],
    ["Active window","The date range during which the current governing condition remains authoritative."],
    ["Near-term path","Up to three meaningful changes across the next 45 days; minor events are excluded."],
    ["24-month astro potential","The measured runway for repeated expansion, leadership durability and survival through pressure."],
    ["Principal risk","The strongest interruption that could override or delay the otherwise supportive structure."],
    ["Chart confidence","Reliability of the approved natal basis—not confidence that a market outcome must occur."],
    ["Turning point (inflection)","A direction-neutral transition field: an existing trend may accelerate, stall, reverse or rotate. Each stock’s natal contacts determine whether it expresses as support or pressure."],
    ["Watch","A turning-point or volatility field whose direction is not predetermined and depends on each stock’s natal response."]
  ];
  return <details className="reading-guide" id="reading-guide"><summary><span><b>Reading guide</b><small>Plain-English phase definitions, colour meanings and methodology notes</small></span><i>＋</i></summary><div className="guide-colours"><span className="macro-tag neutral">neutral</span><p>Balanced or no dominant force</p><span className="macro-tag expansion">expansion</span><p>Supportive or rerating-oriented</p><span className="macro-tag pressure">pressure</span><p>Compression, restraint or structural stress</p><span className="macro-tag watch">watch</span><p>Turning point or volatility; direction is not predetermined</p></div><section className="guide-section"><div className="guide-heading"><span className="eyebrow">How to read the phases</span><h3>What Fin-Lumen’s recurring terms mean</h3><p>Each phrase describes the balance and maturity of astrological structure. It does not predict a financial return.</p></div><div className="phase-grid">{phases.map(([term,meaning])=><div key={term}><b>{term}</b><p>{meaning}</p></div>)}</div></section><section className="guide-section guide-reference"><div className="guide-heading"><span className="eyebrow">Table reference</span><h3>Scores, windows and confidence</h3></div><div className="term-grid">{terms.map(([term,meaning])=><div key={term}><b>{term}</b><p>{meaning}</p></div>)}</div></section></details>
}

function AddStockModal({stocks,watchlist,onRequestAdd,onClose}:{stocks:Stock[];watchlist:string[];onRequestAdd:(value:string)=>Promise<AddResult>;onClose:()=>void}){
  const [query,setQuery]=useState("");const [checked,setChecked]=useState(false);const [loading,setLoading]=useState(false);const [result,setResult]=useState<AddResult|null>(null);
  const normalized=cleanTicker(query);const known=stocks.find(s=>s.ticker===normalized||s.name.toUpperCase()===query.trim().toUpperCase());
  const check=async()=>{setChecked(true);setResult(null);if(known)return;setLoading(true);try{setResult(await onRequestAdd(query))}catch(error){setResult({status:"error",message:error instanceof Error?error.message:"The company could not be added."})}finally{setLoading(false)}};
  const addKnown=async()=>{if(!known)return;setLoading(true);try{setResult(await onRequestAdd(known.ticker))}catch(error){setResult({status:"error",message:error instanceof Error?error.message:"The company could not be added."})}finally{setLoading(false)}};
  const reset=(value:string)=>{setQuery(value);setChecked(false);setResult(null)};
  return <div className="drawer-backdrop modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><section className="add-modal" role="dialog" aria-modal="true" aria-label="Add a stock"><button className="close" onClick={onClose}>×</button><span className="eyebrow">Add to My Stocks · {watchlist.length}/100</span><h2>Enter a company or ticker.</h2><p>One check searches approved readings first. If none exists, Fin-Lumen automatically pulls the official exchange record and prepares its natal candidate for verification.</p><div className="add-search"><input autoFocus value={query} onChange={e=>reset(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")void check()}} placeholder="For example: IRFC.NS or MARUTI.NS"/><button onClick={()=>void check()} disabled={!query.trim()||loading||watchlist.length>=100}>{loading?"Checking…":"Find company"}</button></div>{loading&&<p className="checking-note">Searching approved readings and official exchange evidence. A new company may take a few seconds.</p>}{!checked&&<div className="suggestions"><span>{ENGINE_SUPPORTED_SYMBOLS.length} engine-supported symbols · try:</span>{["MARUTI","ABB","HINDUNILVR","COCHINSHIP"].map(x=><button key={x} onClick={()=>reset(x)}>{x}</button>)}</div>}
      {checked&&known&&<div className="availability available"><span>✓</span><div><b>Approved reading available</b><p>{watchlist.includes(known.ticker)?`${known.name} is already in My Stocks.`:`${known.name} can be restored immediately from its cached reading.`}</p><small>{known.chart} · {known.confidence}/100 reliability{known.cacheState==="browser"?" · browser cache":""}</small></div><button disabled={watchlist.includes(known.ticker)||loading} onClick={()=>void addKnown()}>{watchlist.includes(known.ticker)?"Already added":loading?"Adding…":"Add company"}</button></div>}
      {result?.status==="added"&&!known&&<div className="availability available"><span>✓</span><div><b>Added to My Stocks</b><p>{result.message}</p><small>Its approved reading is now available without recalculating the rest of the table.</small></div><button onClick={onClose}>View table</button></div>}
      {result&&["preparing-evidence","candidate-ready","owner-review"].includes(result.status)&&<div className={`availability ${result.status==="owner-review"?"reviewing":"preparing"}`}><span>{result.status==="owner-review"?"◇":result.status==="candidate-ready"?"✓":"◷"}</span><div><b>{result.status==="owner-review"?"Owner verification required":result.status==="candidate-ready"?"Official listing candidate prepared":"Company request recorded"}</b><p>{result.message}</p><small>No reading will appear until official evidence is checked and a natal basis is approved.</small></div><button onClick={onClose}>Done</button></div>}
      {result&&!["added","preparing-evidence","candidate-ready","owner-review"].includes(result.status)&&<div className={`availability ${result.status==="engine-unreachable"||result.status==="error"?"preparing":"unavailable"}`}><span>{result.status==="engine-unreachable"?"↻":"○"}</span><div><b>{result.status==="engine-unreachable"?"Astro engine temporarily unavailable":result.status==="identity-needed"?"Exact ticker needed":"Official company record not found"}</b><p>{result.message}</p><small>{result.status==="identity-needed"?"Use an exchange ticker so the legal company is not guessed.":"Nothing has been added to the approved universe."}</small></div><button onClick={()=>{setChecked(false);setResult(null)}}>{result.status==="identity-needed"?"Enter ticker":"Try again"}</button></div>}
      {watchlist.length>=100&&<p className="capacity-note">Your personal table has reached its 100-company limit. Remove one company before adding another.</p>}
    </section></div>
}

function AdmissionQueue(){
  const [requests,setRequests]=useState<AdmissionRequest[]>([]);const [loading,setLoading]=useState(false);const [loaded,setLoaded]=useState(false);
  const load=async()=>{if(loaded||loading)return;setLoading(true);try{const response=await fetch("/api/company-admissions",{headers:{accept:"application/json"}});const payload=await response.json() as {requests?:AdmissionRequest[]};setRequests(payload.requests||[]);setLoaded(true)}catch{}finally{setLoading(false)}};
  return <details className="admission-queue" onToggle={event=>{if(event.currentTarget.open)void load()}}><summary><span><span className="eyebrow">Universe development</span><b>New company admission queue</b><small>Requested companies remain outside published readings until their natal basis is approved.</small></span><i>＋</i></summary><div className="admission-body">{loading&&<p>Loading company requests…</p>}{loaded&&requests.length===0&&<p>No new companies are awaiting verification.</p>}{requests.map(request=><article key={request.id}><div><b>{request.companyName}</b><small>{request.symbol} · {request.exchange} · requested {request.requestCount} time{request.requestCount===1?"":"s"}{request.isin?` · ${request.isin}`:""}</small></div><span className={`admission-status ${request.status}`}>{request.status==="owner-review"?"Owner review":request.status==="candidate-ready"?"Candidate ready":request.status==="needs-evidence"?"Needs evidence":"Evidence preparation"}</span><p>{request.evidenceStage}{request.listingDate?` · Listing ${request.listingDate}`:""}</p></article>)}</div></details>
}
