"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";

type ReviewRow = {id:number;symbol:string;company_name:string;exchange:string;status:string;classification:string;evidence_stage:string;listing_evidence_url:string;corporate_evidence_url:string;isin:string|null;listing_date:string|null;candidate_chart_type:string|null;candidate_date:string|null;candidate_time:string|null;candidate_city:string|null;candidate_timezone:string|null;source_label:string|null;history_flags_json:string;request_count:number;owner_note:string|null};

function registryRecord(row:ReviewRow){return {symbol:row.symbol,companyName:row.company_name,preferredChartId:"listing",auditStatus:"source-verified-anchor-untested",sourceVerification:"verified-primary-source",anchorValidation:"untested",timePrecision:"exchange-open-default",capitalAuthorityCeiling:"RESEARCH_ONLY",confidence:"research-candidate",charts:[{id:"listing",chartType:"listing",date:row.candidate_date,time:row.candidate_time,city:row.candidate_city,country:"India",timezone:row.candidate_timezone,confidence:"source-verified-research-candidate",source:`${row.source_label}; ISIN ${row.isin||"not recorded"}. 09:15 Mumbai is a declared session proxy.`}]}}

export default function OwnerReview(){const [rows,setRows]=useState<ReviewRow[]>([]);const [loading,setLoading]=useState(true);const [filter,setFilter]=useState("open");const [notes,setNotes]=useState<Record<number,string>>({});const [notice,setNotice]=useState("");
  const load=async()=>{setLoading(true);try{const response=await fetch("/api/company-admissions/review");const payload=await response.json() as {requests?:ReviewRow[];error?:string};if(!response.ok)throw new Error(payload.error);setRows(payload.requests||[])}catch(error){setNotice(error instanceof Error?error.message:"Review queue unavailable.")}finally{setLoading(false)}};
  useEffect(()=>{let active=true;void fetch("/api/company-admissions/review").then(async response=>{const payload=await response.json() as {requests?:ReviewRow[];error?:string};if(!response.ok)throw new Error(payload.error);if(active)setRows(payload.requests||[])}).catch(error=>{if(active)setNotice(error instanceof Error?error.message:"Review queue unavailable.")}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[]);
  const visible=useMemo(()=>rows.filter(row=>filter==="all"||filter==="open"&&!["approved-for-export","declined"].includes(row.status)||row.status===filter),[rows,filter]);
  const act=async(row:ReviewRow,action:string)=>{setNotice("");const response=await fetch("/api/company-admissions/review",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({id:row.id,action,note:notes[row.id]||""})});if(!response.ok){setNotice("The review decision could not be saved.");return}await load()};
  const copy=async(row:ReviewRow)=>{await navigator.clipboard.writeText(JSON.stringify(registryRecord(row),null,2));setNotice(`${row.symbol} engine record copied. It is still not published until added to the version-controlled registry.`)};
  return <div className="owner-review-app"><div className="review-toolbar"><div><span className="eyebrow">Natal admission service</span><h1>Owner review queue</h1><p>Official evidence may prepare a candidate. Only your decision can prepare it for engine export.</p></div><div><select value={filter} onChange={event=>setFilter(event.target.value)}><option value="open">Open cases</option><option value="candidate-ready">Listing candidates</option><option value="owner-review">Complex history</option><option value="needs-evidence">Needs evidence</option><option value="approved-for-export">Approved for export</option><option value="all">All cases</option></select><Link href="/">Return to dashboard</Link></div></div>{notice&&<p className="review-notice">{notice}</p>}{loading?<p className="review-loading">Loading verification cases…</p>:<div className="review-list">{visible.map(row=>{let flags:string[]=[];try{flags=JSON.parse(row.history_flags_json||"[]")}catch{}return <article key={row.id} className="review-case"><header><div><span>{row.symbol} · {row.exchange}</span><h2>{row.company_name}</h2><small>Requested {row.request_count} time{row.request_count===1?"":"s"}</small></div><b className={`review-status ${row.status}`}>{row.status.replaceAll("-"," ")}</b></header><div className="review-evidence"><div><small>OFFICIAL IDENTITY</small><b>{row.isin||"Not yet resolved"}</b><a href={row.listing_evidence_url} target="_blank" rel="noreferrer">Open exchange evidence ↗</a></div><div><small>LISTING CANDIDATE</small><b>{row.candidate_date?`${row.candidate_date} · ${row.candidate_time} · ${row.candidate_city}`:"Not yet prepared"}</b><span>{row.source_label||row.evidence_stage}</span></div><div><small>CORPORATE HISTORY</small><b>{flags.length?flags.join(" · "):"No NSE name/symbol flag found"}</b><a href={row.corporate_evidence_url} target="_blank" rel="noreferrer">Check MCA master data ↗</a></div></div><p className="review-stage">{row.evidence_stage}</p><label className="review-note"><span>OWNER NOTE</span><textarea value={notes[row.id]??row.owner_note??""} onChange={event=>setNotes(current=>({...current,[row.id]:event.target.value}))} placeholder="Record incorporation, merger or replay-validation findings here."/></label><footer><button className="needs" onClick={()=>void act(row,"needs-evidence")}>Needs more evidence</button><button className="decline" onClick={()=>void act(row,"decline")}>Decline</button><button className="approve" disabled={!row.candidate_date} onClick={()=>void act(row,"approve-export")}>Approve for engine export</button>{row.status==="approved-for-export"&&<button className="copy" onClick={()=>void copy(row)}>Copy registry record</button>}</footer></article>})}{visible.length===0&&<p className="review-empty">No cases match this view.</p>}</div>}</div>}
